openapi: 3.0.0
info:
  title: Website Service
  version: 1.0.0
paths:
  /api/game:
    get:
      description: Generate a new game.
      parameters:
        - in: query
          name: deck
          schema:
            type: string
      responses:
        "200":
          description: Successful handling.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Game"
        "429":
          description: Too many requests.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
        "500":
          description: Internal Error.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
  /api/submit:
    post:
      description: Submit a game outcome.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../types.yaml#/components/schemas/Game"
      responses:
        "200":
          description: Successful handling.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Result"
        "401":
          description: Expired or malformed token.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
        "403":
          description: Duplicate game submission.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
        "429":
          description: Too many requests.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
        "500":
          description: Internal Error.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
